[package]
name = "pensieve"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
log = "0.4.27"
lru = "0.14.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
