version: '3.9'

services:
  node1:
    build: .
    environment:
      PORT: "8001"
      NODE_ID: "1"
      PEERS: "http://node2:7878,http://node3:7878"
    ports:
      - "8001:7878"

  node2:
    build: .
    environment:
      PORT: "8002"
      NODE_ID: "2"
      PEERS: "http://node1:7878,http://node3:7878"
    ports:
      - "8002:7878"

  node3:
    build: .
    environment:
      PORT: "8003"
      NODE_ID: "3"
      PEERS: "http://node1:7878,http://node2:7878"
    ports:
      - "8003:7878"
